services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@safecity.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - database