<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260725133000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute la file de modération récupérable pour les commentaires et les photos.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE moderation_case (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reporter_id INT DEFAULT NULL, author_id INT DEFAULT NULL, moderator_id INT DEFAULT NULL, target_type VARCHAR(255) NOT NULL, target_id INT NOT NULL, reason VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, reported_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, moderated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B3D05FEAE1CFE6F5 ON moderation_case (reporter_id)');
        $this->addSql('CREATE INDEX IDX_B3D05FEAF675F31B ON moderation_case (author_id)');
        $this->addSql('CREATE INDEX IDX_B3D05FEAD0AFA354 ON moderation_case (moderator_id)');
        $this->addSql('CREATE INDEX IDX_B3D05FEACB24C6F8 ON moderation_case (target_type, target_id, status)');
        $this->addSql('ALTER TABLE moderation_case ADD CONSTRAINT FK_B3D05FEAE1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE moderation_case ADD CONSTRAINT FK_B3D05FEAF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE moderation_case ADD CONSTRAINT FK_B3D05FEAD0AFA354 FOREIGN KEY (moderator_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('COMMENT ON COLUMN moderation_case.reported_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN moderation_case.moderated_at IS \'(DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE moderation_case');
    }
}
