<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Retire définitivement les prévisions, alertes et préférences météo.
 */
final class Version20260729223000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Supprime tout le périmètre météo devenu hors périmètre de SafeCity.';
    }

    public function up(Schema $schema): void
    {
        // Le type PHP disparaît avec ce lot : ses éventuelles notifications
        // doivent être retirées avant le prochain chargement Doctrine.
        $this->addSql("DELETE FROM notification WHERE type = 'weather'");

        $this->addSql('ALTER TABLE weather_alert DROP CONSTRAINT FK_3EBA0CC38BAC62AF');
        $this->addSql('DROP TABLE weather_alert');
        $this->addSql('ALTER TABLE profile DROP weather_notifications');
    }

    public function down(Schema $schema): void
    {
        // La structure peut être reconstruite, mais les notifications météo
        // supprimées par up() ne peuvent pas être restaurées automatiquement.
        $this->addSql('ALTER TABLE profile ADD weather_notifications BOOLEAN DEFAULT TRUE NOT NULL');
        $this->addSql('ALTER TABLE profile ALTER weather_notifications DROP DEFAULT');
        $this->addSql('CREATE TABLE weather_alert (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, gravity_level VARCHAR(255) NOT NULL, message TEXT NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3EBA0CC38BAC62AF ON weather_alert (city_id)');
        $this->addSql('ALTER TABLE weather_alert ADD CONSTRAINT FK_3EBA0CC38BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
    }
}


