<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Ajoute la chronologie persistante des statuts de signalement.
 */
final class Version20260729203000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute l’historique daté des statuts et reprend les signalements existants.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE report_status_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, report_id INT NOT NULL, changed_by_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_REPORT_STATUS_TIMELINE ON report_status_history (report_id, changed_at)');
        $this->addSql('CREATE INDEX IDX_REPORT_STATUS_CHANGED_BY ON report_status_history (changed_by_id)');
        $this->addSql('ALTER TABLE report_status_history ADD CONSTRAINT FK_REPORT_STATUS_REPORT FOREIGN KEY (report_id) REFERENCES report (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE report_status_history ADD CONSTRAINT FK_REPORT_STATUS_USER FOREIGN KEY (changed_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        // Tous les signalements possèdent une date d’envoi fiable.
        $this->addSql("INSERT INTO report_status_history (report_id, changed_by_id, status, changed_at) SELECT id, reporter_id, 'reported', created_at FROM report");

        // Pour un ancien état avancé, seule la date du statut courant est connue :
        // aucune étape intermédiaire fictive n’est inventée par la migration.
        $this->addSql("INSERT INTO report_status_history (report_id, changed_by_id, status, changed_at) SELECT id, NULL, status, COALESCE(updated_at, created_at) FROM report WHERE status <> 'reported'");
    }

    public function down(Schema $schema): void
    {
        // Un retour arrière supprimerait uniquement le nouvel historique.
        $this->addSql('ALTER TABLE report_status_history DROP CONSTRAINT FK_REPORT_STATUS_REPORT');
        $this->addSql('ALTER TABLE report_status_history DROP CONSTRAINT FK_REPORT_STATUS_USER');
        $this->addSql('DROP TABLE report_status_history');
    }
}


