<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260725130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les règles administrables de routage des signalements.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE routing_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category_id INT DEFAULT NULL, emergency_service_id INT NOT NULL, gravity_level VARCHAR(255) NOT NULL, priority INT DEFAULT 100 NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_11A4FFFF12469DE2 ON routing_rule (category_id)');
        $this->addSql('CREATE INDEX IDX_11A4FFFFF948F73B ON routing_rule (emergency_service_id)');
        $this->addSql('CREATE INDEX IDX_9F4B13C7C49A7F65 ON routing_rule (gravity_level, enabled, priority)');
        $this->addSql('ALTER TABLE routing_rule ADD CONSTRAINT FK_9F4B13C712469DE2 FOREIGN KEY (category_id) REFERENCES report_category (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE routing_rule ADD CONSTRAINT FK_9F4B13C775C924D9 FOREIGN KEY (emergency_service_id) REFERENCES emergency_service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE routing_rule');
    }
}

