<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630094635 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE city (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, postal_code VARCHAR(10) NOT NULL, department VARCHAR(100) NOT NULL, available BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_id INT DEFAULT NULL, report_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9474526CF675F31B ON comment (author_id)');
        $this->addSql('CREATE INDEX IDX_9474526C4BD2A4C0 ON comment (report_id)');
        $this->addSql('CREATE TABLE emergency_service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(100) NOT NULL, phone VARCHAR(20) NOT NULL, status VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, location VARCHAR(255) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, is_free BOOLEAN NOT NULL, image_url VARCHAR(255) DEFAULT NULL, city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3BAE0AA78BAC62AF ON event (city_id)');
        $this->addSql('CREATE TABLE event_favorite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reminder_active BOOLEAN NOT NULL, added_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, event_user_id INT NOT NULL, event_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2E29670922397A3A ON event_favorite (event_user_id)');
        $this->addSql('CREATE INDEX IDX_2E29670971F7E88B ON event_favorite (event_id)');
        $this->addSql('CREATE TABLE local_service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, latitude NUMERIC(10, 7) NOT NULL, longitude NUMERIC(10, 7) NOT NULL, phone VARCHAR(20) DEFAULT NULL, on_duty BOOLEAN NOT NULL, opening_hours TEXT DEFAULT NULL, city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7C489F5F8BAC62AF ON local_service (city_id)');
        $this->addSql('CREATE TABLE news (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, source VARCHAR(255) DEFAULT NULL, category VARCHAR(50) NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, image_url VARCHAR(255) DEFAULT NULL, city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1DD399508BAC62AF ON news (city_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, type VARCHAR(255) NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_read BOOLEAN NOT NULL, recipient_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAE92F8F78 ON notification (recipient_id)');
        $this->addSql('CREATE TABLE parking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, latitude NUMERIC(10, 7) NOT NULL, longitude NUMERIC(10, 7) NOT NULL, is_free BOOLEAN NOT NULL, available_spots INT NOT NULL, total_spots INT NOT NULL, city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B237527A8BAC62AF ON parking (city_id)');
        $this->addSql('CREATE TABLE photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(255) NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, uploader_id INT DEFAULT NULL, report_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_14B7841816678C77 ON photo (uploader_id)');
        $this->addSql('CREATE INDEX IDX_14B784184BD2A4C0 ON photo (report_id)');
        $this->addSql('CREATE TABLE profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, emergency_notifications BOOLEAN NOT NULL, weather_notifications BOOLEAN NOT NULL, transport_notifications BOOLEAN NOT NULL, event_notifications BOOLEAN NOT NULL, microphone_access BOOLEAN NOT NULL, camera_access BOOLEAN NOT NULL, location_access BOOLEAN NOT NULL, language VARCHAR(10) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT DEFAULT NULL, gravity_level VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, latitude NUMERIC(10, 7) NOT NULL, longitude NUMERIC(10, 7) NOT NULL, address VARCHAR(255) DEFAULT NULL, audio_url VARCHAR(255) DEFAULT NULL, audio_language VARCHAR(10) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reporter_id INT DEFAULT NULL, category_id INT NOT NULL, emergency_service_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C42F7784E1CFE6F5 ON report (reporter_id)');
        $this->addSql('CREATE INDEX IDX_C42F778412469DE2 ON report (category_id)');
        $this->addSql('CREATE INDEX IDX_C42F7784F948F73B ON report (emergency_service_id)');
        $this->addSql('CREATE TABLE report_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, icon VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE transport (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, line VARCHAR(50) NOT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL, disruption TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_66AB212E8BAC62AF ON transport (city_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, google_id VARCHAR(255) DEFAULT NULL, registration_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, role VARCHAR(255) NOT NULL, cgu_accepted BOOLEAN NOT NULL, account_active BOOLEAN NOT NULL, city_id INT DEFAULT NULL, profile_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D6498BAC62AF ON "user" (city_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649CCFA12B8 ON "user" (profile_id)');
        $this->addSql('CREATE TABLE weather_alert (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, gravity_level VARCHAR(255) NOT NULL, message TEXT NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3EBA0CC38BAC62AF ON weather_alert (city_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C4BD2A4C0 FOREIGN KEY (report_id) REFERENCES report (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA78BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_favorite ADD CONSTRAINT FK_2E29670922397A3A FOREIGN KEY (event_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_favorite ADD CONSTRAINT FK_2E29670971F7E88B FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE local_service ADD CONSTRAINT FK_7C489F5F8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT FK_1DD399508BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAE92F8F78 FOREIGN KEY (recipient_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE parking ADD CONSTRAINT FK_B237527A8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B7841816678C77 FOREIGN KEY (uploader_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B784184BD2A4C0 FOREIGN KEY (report_id) REFERENCES report (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F778412469DE2 FOREIGN KEY (category_id) REFERENCES report_category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784F948F73B FOREIGN KEY (emergency_service_id) REFERENCES emergency_service (id)');
        $this->addSql('ALTER TABLE transport ADD CONSTRAINT FK_66AB212E8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6498BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649CCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile (id)');
        $this->addSql('ALTER TABLE weather_alert ADD CONSTRAINT FK_3EBA0CC38BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526CF675F31B');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C4BD2A4C0');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA78BAC62AF');
        $this->addSql('ALTER TABLE event_favorite DROP CONSTRAINT FK_2E29670922397A3A');
        $this->addSql('ALTER TABLE event_favorite DROP CONSTRAINT FK_2E29670971F7E88B');
        $this->addSql('ALTER TABLE local_service DROP CONSTRAINT FK_7C489F5F8BAC62AF');
        $this->addSql('ALTER TABLE news DROP CONSTRAINT FK_1DD399508BAC62AF');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAE92F8F78');
        $this->addSql('ALTER TABLE parking DROP CONSTRAINT FK_B237527A8BAC62AF');
        $this->addSql('ALTER TABLE photo DROP CONSTRAINT FK_14B7841816678C77');
        $this->addSql('ALTER TABLE photo DROP CONSTRAINT FK_14B784184BD2A4C0');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784E1CFE6F5');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F778412469DE2');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784F948F73B');
        $this->addSql('ALTER TABLE transport DROP CONSTRAINT FK_66AB212E8BAC62AF');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6498BAC62AF');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649CCFA12B8');
        $this->addSql('ALTER TABLE weather_alert DROP CONSTRAINT FK_3EBA0CC38BAC62AF');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE emergency_service');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE event_favorite');
        $this->addSql('DROP TABLE local_service');
        $this->addSql('DROP TABLE news');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE parking');
        $this->addSql('DROP TABLE photo');
        $this->addSql('DROP TABLE profile');
        $this->addSql('DROP TABLE report');
        $this->addSql('DROP TABLE report_category');
        $this->addSql('DROP TABLE transport');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE weather_alert');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
